---
title: "White Paper"
editor: visual
---

**The Experience of Serious Risk-Taking Behaviors in Bipolar Disorders: Exploring the Potential for Co-Design Resources within Community Support Groups.**

Guillermo Perez Algorta, David Dinham & Emmanuel Tsekleves

*What is the problem?*

Bipolar disorder (BD) is a mental health condition that affects people's mood, thoughts, and behaviors. It is characterised by severe changes in mood and energy levels that cause significant impairment in people life. It is estimated that BD affects \~60 million people globally. In the UK alone, \~1 million could be experiencing the impact of BD. People with BD often engage in serious risk-taking behaviours. Examples include substance misuse and alcohol, crimes, sexual misconduct, and reckless financial activities. Engaging in these behaviors can carry negative outcomes including; experiencing long mood episodes, worsened course of the condition, and fatal situations such as suicide or death by accidents. Shame and regret are often common experiences when people reflect on these negative past events. Anxiety about making future decisions and engaging in risk (not necessarily serious risk taking) can also be a legacy of these experiences. These serious risk behaviours can also have a profound negative social impact, for example, affecting relationships with family, friends or professional acquaintances. Despite the challenges that people with BD can face, they also express a clear sense of satisfaction when they are better able to manage these risks in daily life (Wah et al. 2021).

To our knowledge, there are no specific interventions aimed at preventing engagement in these serious situations, other than indirect interventions focused on mood regulation. These serious risk behaviours tend to be conceptualised as manifestations of high impulsivity or disordered mood. The reduction of serious risk-taking is currently secondary to treatments in BD, and targeted mechanism of risk taking often lean toward biological rather than behavioral approaches. Psychological interventions aimed at preventing or reducing risk taking behaviours are typically grounded in the concept that providing individuals with detailed information about the risk and benefits of their decisions is crucial. These interventions employ a problem-solving approach, where optimal decision-making results from a careful trade-off of risks and benefits, ultimately increasing likelihood of avoiding serious risky choices. Regrettably, this approach is not universally effective, and in some cases, it may even produce contrary effects, such as an increase in risk-taking behaviour, as suggested by the Fuzzy Trace Theory (e.g., Reyna & Mills, 2014) and our previous studies (Sicilia et al. 2020, Lukacs et al. 2021).

*Our proposal to address the issue.*

Informed by our previous research, we have identified resources to create capacity-building initiatives for managing risk behaviours in the daily lives of individuals with BD. With these resources, our approach aims to address risky behaviours and beliefs by promoting a nuanced understanding of one's own values, thought processes, reasoning, and bias related to risk, drawing insights from Fuzzy Trace Theory (FTT).\
According to FTT, qualitative, bottom-line, or "gist" reasoning tends to lead to less risk taking behavior, and is less easily swayed by emotions and impulsivity compared to quantitative, detail-oriented, or "verbatim" reasoning. As mentioned earlier, for the minority of individuals who receive psychological treatment, the prevailing approach to addressing these issues is based on problem-solving strategies, evaluating pros and cons (relying on verbatim reasoning), which, in accordance with FTT and our previous findings, could potentially yield negative outcomes.

\
Similar to the outcomes of interventions informed by FTT aimed at addressing risk in various groups, our previous research involving individuals with BD revealed that elevated levels of gist reasoning in BD, even when controlling for significant confounding variables, such as age, mania and impulsivity, attenuate the association between impulsivity and risk-taking. This gist reasoning appears to act as a protective factor against impulsive behaviours that carry risk. Importantly, this buffering effect was particularly pronounced in individuals with high levels of impulsivity (possibly more severe clinical cases) (Lukacs et al. 2021). The central aspect of this proposal revolves around increasing people's understanding of the advantages associated with extracting the bottom line meaning or "gist" of daily life situations involving risk. This is accomplished by offering training opportunities designed to increase the likelihood of employing this type of information processing, i.e., extracting the bottom line meaning, when encountering everyday situations involving risk. In addition to this, we aim to increase individuals' appreciation of the benefits derived from recognising and contemplating their personal life values. To achieve this, we offer training opportunities aimed at increasing the likelihood of connecting the bottom line meaning of daily life situations involving risk with people own life values. One illustrative activity in our proposal involves the interpretation of proverbs. By using proverbs such as "People who live in glass houses should not throw stones", "An ounce of prevention is worth a pounce of cure", or "A stich in times saves nine", participants have the opportunity to engage in the practice of extracting the bottom line meaning of a given situation. Simultaneously, they are encouraged to filling in the gaps with their own personal values and perspectives.

\
The ability to extract the bottom line meaning within the framework of one's personal values is what we anticipate should come into place when individuals encounter a serious risk situation in their daily lives. For instance, when faced with the prospect of engaging in unprotected intercourse, it would be beneficial to recall that that "it only takes once to get HIV-AIDS" (representing the bottom line meaning or gist) and to acknowledge that "I have a responsibility to my partner to not put him/her at risk" (reflecting a personal value). This approach posits that by connecting these key elements (the gist and personal values), the likelihood of engaging in such a risky situation could be reduced. To complement these activities, we will work around four themes that emerged from our exploration of the life experiences of individuals with BD in relation to risk (Wah et al. 2021). These themes are: "True Self and Risk" "Empowerment, Sense of Control and Self-Compassion" "Intolerance of Uncertainty in the Context of Risk (What Ifs)" "Systemic-Relational Aspects Relevant to Risk (Communication, Negotiation, and Expressed Emotions)" For each of these themes, we have designed specific activities that are grounded in relevant theoretical models, such as the Intolerance of Uncertainty model, to guide our approach. In summary, our approach diverges from the prevailing medical model, which typically portrays risk as a negative outcome beyond our control. Instead, we conceptualise risk as a process within our control, aligning with individuals' expectations and desires, while acknowledging that it may still carry the potential for negative consequences. Furthermore, addressing issues related to risk-taking through the autonomous process of decision making has the potential to enhance individuals' feelings of self-efficacy and control. This in turn, may yield positive effects on their overall well-being, and it could also contribute to the feasibility and acceptability of these activities. The resources presented here intend to enhance risk management specifically for individuals with BD during periods outside manic episodes or severe depression.

\
This limitation does not diminish the value of this proposal, as individual with BD typically spend a relatively small portion of their lives experiencing severe mood episodes. For most of their time, they transition between euthymia (normal mood), various levels of depression (low mood), and hypomania (heightened mood but not extreme mania). During these periods, cognitive functioning including decision making abilities, is not expected to be severely compromised.

*How are we going to address the problem(s)?*

Why community support groups? We have identified community support groups (CSG) as one potential space to implement these activities. CGS are popular and cost-effective options, addressing various challenges experienced by people worldwide. In the UK, the majority of CSG tend to be assets base rather than deficit based in their approach to tackle challenges. They aim to empower people to enhance the skills they already possess, in contrast to traditional clinical models. Individuals attending community support groups seek to better manage their conditions. These initiatives focus on recovery, empowering participants to thrive despite challenges associated with conditions such as BD. Conceptualising the factors at play within CSG is not straightforward. Some proposals emphasise the role of factors such as identity, mentalisation, values, and storytelling (add ref). Others mention the impact of CSG on power dynamics (add ref), where individuals find a place to make decisions for themselves rather than being told what to do. Life experience plays a crucial role in CSG: a liminal position of "I've experienced, I've learned, and I want to share (add ref?). CSG provide a platform for intergenerational transmission of experiential learning. For instance, young people can use CSGs as a mean to expand their understanding of risk beyond being just one of their bipolar symptoms. Participation in CSG offers them a chance to contemplate the significant potential and enduring consequences of these experiences in their lives. For young individuals, CSGs can serve as a preventative space to mitigate the adverse effects of engaging in serious risk behaviors. For adults who have accumulated extensive life experiences, the discussions that occur within CSG context concerning serious risk can be opportunities to sharing losses, explore bereavement, and discover that they are not alone in their experiences:"Is not just me!" . GSG provide opportunities to acquire and hone strategies for managing anxiety in the context of decision making. They serve as a platform for implementing self-compassion and addressing issues related to stigma and self-stigma. Additionally, they facilitate the examination and application of communication strategies with relevant others. CSG are inclusive spaces that encompass various methods of learning and communication, including the arts, as well as opportunities for social interactions and shared experiences.

*How are we addressing the problem(s)?*

Why co-production/co-design? While community support groups provide a promising avenue, effectively implementing activities to reduce risk behaviours in bipolar disorder also requires a co-design approach. Co-design refers to collective creativity across the whole span of a design process, engaging all stakeholders in proposing solutions, rather than limiting participation to just feedback on predefined options (Sanders and Stappers, 2008). For this intervention, a co-design format enables incorporating lived expertise and values from people with bipolar disorder alongside clinical and research perspectives. This integration of diverse forms of knowledge can enhance relevance, feasibility and acceptability of the resources offered to support risk behaviour change (Steen, 2013). Through collaborative workshops, people with bipolar disorder can directly shape activities based on what makes sense and motivates their own behaviour change, rather than just responding to researcher's assumptions. Initial workshops will focus on identifying values, goals, challenges and resources related to risk behaviours in daily life. Creative activities like future envisioning, perspective-taking, and metaphor elicitation can prompt sharing of diverse views. Visual models will capture collective insights on risk factors and potential intervention directions. In later workshops, participants will collaboratively prototype concrete activities, formats and materials to support the proposed skills training around gist reasoning and values reflection. Rapid feedback loops enable quick iteration. Throughout the process, the designer-researchers will facilitate dialogue, visualize patterns and synthesize insights toward coherent intervention pathways. However, the collaborators with bipolar disorder play the central role in steering the direction and shaping solutions. Their experiential expertise provides the core guiding framework for determining how to best address risky behaviours in sensitive, empowering, and pragmatically actionable ways. This co-design approach embraces open-endedness rather than predefined solutions. It redistributes creative agency among diverse stakeholders in the service of mutual learning to meet collective goals. While intensive, this collaborative discovery process promises to yield novel interventions closely aligned with the lived realities of people with bipolar disorder. The resulting activities and formats will reflect the priorities, values, and mental models of those who will ultimately use the resources. In this way, integrating co-design into intervention development maximizes relevance, acceptability and real-world viability. To articulate this complexity, we are opening a "phygital" collaborative space. Phygital refers to a combination of physical and online environments. To guide and shape this phygital space, we are inspired by the concept of community allotments and gardens.\
Community allotment and gardens are tangible spaces found throughout the UK, which make the most of relatively small parcels of land to produce something of value. They require active engagement and have a recognised positive impact on wellbeing. They rely on individual's responsible behaviors, promoting and embracing values of knowledge exchange and diversity. They offer a dynamic ecosystem where sustainability is paramount, guided by clear rules resulting in safe spaces for users. They are also transparent and easy to replicate. Overall, addressing complex health issues like risk behaviours in bipolar disorder requires crossing boundaries between disciplines and between research and practice. Co-design provides a constructive framework for this interdisciplinary collaboration, joint inquiry and knowledge exchange. By enabling people with lived expertise to actively shape solutions tailored to their self-defined needs, co-design holds transformative potential for health interventions and services. This human-centred methodology puts collective wellbeing over singular expertise, illuminating more holistic pathways forward.

**References**

Wah, A., Hodge, S., Jones, S. H., & Algorta, G. P. (2021). A qualitative exploration of how people with bipolar disorder consider risk-taking in everyday decisions. Behavioural and Cognitive Psychotherapy, 49(3), 314--327.

Reyna, V. F., & Mills, B. A. (2014). Theoretically motivated interventions for reducing sexual risk taking in adolescence: A randomized controlled experiment applying fuzzy-trace theory. Journal of Experimental Psychology: General, 143, 1627--1648. <https://doi.org/10.1037/a0036717>

Sicilia, A. C., Lukacs, J. N., Jones, S., & Perez Algorta, G. (2020). Decision-making and risk in bipolar disorder: A quantitative study using fuzzy trace theory. Psychology and Psychotherapy: Theory, Research and Practice, 93(1), 105--121.

Lukacs, J. N., Sicilia, A. C., Jones, S., & Algorta, G. P. (2021). Interactions and implications of Fuzzy-Trace theory for risk taking behaviors in bipolar disorder. Journal of Affective Disorders, 293, 305--313. Sanders, E. B. N., &

Stappers, P. J. (2008). Co-creation and the new landscapes of design. Co-design, 4(1), 5-18. Steen, M. (2013). Co-design as a process of joint inquiry and imagination. Design issues, 29(2), 16-28.
